/// <reference types="vite/client" />

/** True in the single-file build (`vite build --mode single`). */
declare const __P5_SINGLE__: boolean;

/** The wasm module as base64 in the single-file build, otherwise null. */
declare module "virtual:player5/wasm" {
  const wasmBase64: string | null;
  export default wasmBase64;
}

/** URL of the wasm module: content-hashed in a build, public/ in dev. */
declare module "virtual:player5/wasm-url" {
  const wasmUrl: string;
  export default wasmUrl;
}

/** The wasm2js build of the core (generated by scripts/gen-core.mjs). */
declare module "virtual:player5/core-js" {
  export function createCore(): unknown;
}
