[package]
name = "sequencer"
description = "player5 step sequencer, event model, lock-free event queue and lookahead scheduler"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
sync.workspace = true

[lints]
workspace = true
